### ISSUE TITLE
Support for Python3.14

### ISSUE THREAD

**Issue by BwL1289** [BrianPugh/cyclopts#795]
Is there planned support for Python3.14? 

```bash
File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1912, in __call__
    command, bound, _ = self.parse_args(
                        ~~~~~~~~~~~~~~~^
        tokens,
        ^^^^^^^
        console=console,
        ^^^^^^^^^^^^^^^^
        end_of_options_delimiter=end_of_options_delimiter,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1794, in parse_args
    command, bound, _, ignored, _ = self._parse_known_args(
                                    ~~~~~~~~~~~~~~~~~~~~~~^
        tokens,
        ^^^^^^^
        raise_on_unused_tokens=True,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1649, in _parse_known_args
    argument_collection = command_app.assemble_argument_collection()
  File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1511, in assemble_argument_collection
    return ArgumentCollection._from_callable(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.default_command,  # pyright: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        parse_docstring=parse_docstring,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 444, in _from_callable
    iparam_argument_collection = cls._from_type(
        field_info,
    ...<9 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 375, in _from_type
    subkey_argument_collection = cls._from_type(
        sub_field_info,
    ...<14 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 375, in _from_type
    subkey_argument_collection = cls._from_type(
        sub_field_info,
    ...<14 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 271, in _from_type
    cyclopts_parameters.append(group.default_parameter)
                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ForwardRef' object has no attribute 'default_parameter'
[root@55629c692947 /]#
```

**Comment by BrianPugh** [comment]
yes! let me investigate later today.

**Comment by BrianPugh** [comment]
so cyclopts should be working fine on python 3.14 (i'll add the classifier to it soon), but I'm unable to reproduce your error. Is there any way that you can share code (or a minimal reproducable example) that led to this error? I'm not sure if this is a python3.14-specific issue.

**Comment by BwL1289** [comment]
> or a minimal reproducable example

See below. This was w/ `aiperf`

```bash
[root@55629c692947 /]# aiperf profile \
  --model "meta-llama/Llama-3.1-8B-Instruct" \
  --streaming \
  --endpoint-type chat \
  --tokenizer meta-llama/Llama-3.1-8B-Instruct \
  --url http://localhost:8000/
Traceback (most recent call last):
  File "/usr/local/sbin/aiperf", line 6, in <module>
    sys.exit(app())
             ~~~^^
  File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1912, in __call__
    command, bound, _ = self.parse_args(
                        ~~~~~~~~~~~~~~~^
        tokens,
        ^^^^^^^
        console=console,
        ^^^^^^^^^^^^^^^^
        end_of_options_delimiter=end_of_options_delimiter,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1794, in parse_args
    command, bound, _, ignored, _ = self._parse_known_args(
                                    ~~~~~~~~~~~~~~~~~~~~~~^
        tokens,
        ^^^^^^^
        raise_on_unused_tokens=True,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1649, in _parse_known_args
    argument_collection = command_app.assemble_argument_collection()
  File "/usr/local/lib/python3.14/site-packages/cyclopts/[core.py](http://core.py/)", line 1511, in assemble_argument_collection
    return ArgumentCollection._from_callable(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.default_command,  # pyright: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        parse_docstring=parse_docstring,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 444, in _from_callable
    iparam_argument_collection = cls._from_type(
        field_info,
    ...<9 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 375, in _from_type
    subkey_argument_collection = cls._from_type(
        sub_field_info,
    ...<14 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 375, in _from_type
    subkey_argument_collection = cls._from_type(
        sub_field_info,
    ...<14 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/usr/local/lib/python3.14/site-packages/cyclopts/argument/_[collection.py](http://collection.py/)", line 271, in _from_type
    cyclopts_parameters.append(group.default_parameter)
                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ForwardRef' object has no attribute 'default_parameter'
[root@55629c692947 /]#
```

**Comment by BrianPugh** [comment]
thanks! i'm able to reproduce; right now i'm trying to figure out if it's a cyclopts issue or an aiperf issue. I'll update this post when i come to a conclusion.

**Comment by BrianPugh** [comment]
I'm like 90% sure this is a usage issue with cyclopts usage within aiperf. They define a private `_CLI_GROUP` within a pydantic model. This causes the field to not even exist in the class's `__dict__`, which causes `typing.get_type_hints` to also fail to resolve the forward-reference. Basically, by the time Cyclopts gets the `ForwardRef`, there's not enough context to resolve it. I think `aiperf` can solve this by not assigning the group to the intermediate private attribute `_CLI_GROUP`.

Would you mind opening an issue in their repo about this? Thanks!

**Comment by BrianPugh** [comment]
closing for now, as I don't think there's any actionable items for this repo. We can re-open if there's evidence otherwise!

**Comment by ajcasagrande** [comment]
Thanks for the quick triage, @BrianPugh — your hint about `_CLI_GROUP` being a private class attribute was exactly right. Confirmed: under PEP 649 deferred annotation evaluation (3.14 default), `typing.get_type_hints` evaluates the `Annotated[..., CLIParameter(group=_CLI_GROUP)]` expression in module scope where the class-body constant is invisible, so cyclopts receives a `ForwardRef`.

Fixed on the aiperf side by dropping the `_CLI_GROUP` indirection entirely and inlining `Groups.X` at each `CLIParameter(group=...)` call site (`Groups` is module-imported so it resolves cleanly). Verified end-to-end on Python 3.14.3 — full unit suite (8810 tests) passes. PR: ai-dynamo/aiperf#879. Thanks again!

**Comment by BwL1289** [comment]
Thanks all-glad this was resolved.
